### ISSUE TITLE
Got jax.errors.TracerIntegerConversionError when running generate.py

### ISSUE THREAD

**Issue by zhangzx-uiuc** [ayaka14732/llama-2-jax#14]
Thanks for publicizing this great repo! It is really helpful for users who want to finetune llama2 with TRC resources.

I am encountering the following `jax.errors.TracerIntegerConversionError` when trying to run `.legacy/generate.py` with `llama-7b`. Just would like to know if you have any insights on this?

```
Traceback (most recent call last):
  File "/home/zhangzx.uiuc/llama-2-jax/generate.py", line 63, in <module>
    main()
  File "/home/zhangzx.uiuc/llama-2-jax/generate.py", line 55, in main
    generated_seq = top_p(params, seq, attn_mask, key=subkey, model_config=config_llama2_7B_, top_p_config=top_p_config)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^
  File "/home/zhangzx.uiuc/llama-2-jax/lib/generation/top_p.py", line 65, in top_p
    state = while_loop((lambda state: ~jnp.all(state.finished)), loop_body, state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhangzx.uiuc/llama-2-jax/lib/generation/_utils.py", line 5, in while_loop
    val = body_fun(val)
          ^^^^^^^^^^^^^
  File "/home/zhangzx.uiuc/llama-2-jax/lib/generation/top_p.py", line 62, in <lambda>
    loop_body = lambda state: _loop_body_top_p(params, state, model_config, top_p_config)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhangzx.uiuc/llama-2-jax/lib/generation/top_p.py", line 30, in _loop_body_top_p
    logits = jax.vmap(getitem)(outputs, last_positions) @ params.lm_head
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax.errors.TracerIntegerConversionError: The __index__() method was called on traced array with shape int32[].
This BatchTracer with object id 140284154640592 was created on line:
  /home/zhangzx.uiuc/llama-2-jax/lib/generation/top_p.py:30:13 (_loop_body_top_p)
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerIntegerConversionError
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

**Comment by ayaka14732** [comment]
I am currently rewriting the code for generation and this will be fixed soon.

**Comment by ayaka14732** [comment]
This should have been fixed.
